name: stats

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Run tests
        working-directory: ./stats
        run: go test -v ./...
